-- AUTORELACIONAMENTO

USE comercio; 


CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME  VARCHAR(30),
    HORAS INT,
    VALOR FLOAT(10,2),
    ID_PREREQ INT
    );
   
DROP TABLE CURSOS; 
ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

SELECT * FROM CURSOS;

DELETE FROM CURSOS
WHERE IDCURSO = 1;

INSERT INTO CURSOS VALUES(NULL, 'DB RELACIONAL', 20, 400.0, NULL);
INSERT INTO CURSOS VALUES(NULL, 'BUSINESS INTELLIGENCE', 40, 800.0, 1);
INSERT INTO CURSOS VALUES(NULL, 'RELATORIOS AVANÇADOS', 20, 600.0, 2);
INSERT INTO CURSOS VALUES(NULL, 'LOGICA DE PROGRAMAÇÃO', 20, 400.0, NULL);
INSERT INTO CURSOS VALUES(NULL, 'RUBY', 10, 500.0, 4);

SELECT * FROM CURSOS;

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ, "SEM REQUISITOS") REQUISITOS 
FROM CURSOS;

SELECT C.NOME AS CURSO, C.VALOR AS VALOR , C.HORAS AS CARGA, IFNULL(P.NOME, '----') AS PREREQ
FROM CURSOS AS C
LEFT JOIN CURSOS AS P
ON P.IDCURSO = C.ID_PREREQ;
