CREATE DATABASE CURSORES;

USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT
    );
    
INSERT INTO VENDEDORES VALUES(NULL,'MAFRA',32432,242334,574545);
INSERT INTO VENDEDORES VALUES(NULL,'CLARA',65465,65443,653454);
INSERT INTO VENDEDORES VALUES(NULL,'JOAO',12432,65356,8756);
INSERT INTO VENDEDORES VALUES(NULL,'LILIAN',4567,9676,8765);
INSERT INTO VENDEDORES VALUES(NULL,'ANTONIO',3467,68756,99765);
INSERT INTO VENDEDORES VALUES(NULL,'GLORIA',54786,76889,7098);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN+FEV+MAR) AS TOTAL FROM VENDEDORES;
SELECT NOME, (JAN+FEV+MAR) AS TOTAL, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
	NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
    );
    
SELECT * FROM VEND_TOTAL;

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0;
    DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT; -- PARA ALCOAR AS VARIÁVEIS DE VEND_TOTAL
    DECLARE VNOME VARCHAR(50);
    
    DECLARE REG CURSOR FOR(
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
        );
        
        DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
        
        OPEN REG; 
        
        REPEAT
        
			FETCH REG INTO VNOME, VAR1, VAR2, VAR3; -- TRAZ O PRÓXIMO REGISTRO (REG)
			IF NOT FIM THEN
				
                SET VTOTAL = VAR1 + VAR2 + VAR3;
                SET VMEDIA = VTOTAL / 3;
                
                INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1, VAR2,VAR3, VTOTAL, VMEDIA);
            END IF;   
		UNTIL FIM END REPEAT;
        CLOSE REG;
END
$

DELIMITER ;

CALL INSEREDADOS();

SELECT * FROM VEND_TOTAL;
